version: "3"

services:
  nxt-pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - nxt-pg-data:/var/lib/postgres

    networks:
      - nxt-network

    ports:
      - "5432:5432"
networks:
  nxt-network:
    driver: bridge
volumes:
  nxt-pg-data:
